title: Meteoros Floripa
description: Estações de capturas de meteoros em Florianópolis/SC
url: "https://meteoros.floripa.br"
baseurl: "/"
city: "Florianópolis-SC"
encoding: UTF-8
highlighter: rouge
timezone: UTC
permalink: pretty
paginate: 15
pagination_path: "/:num"
google_analytics: "UA-148905542-1"
s3_bucket: "meteoros"
storage_url: "https://meteoros.s3.us-west-000.backblazeb2.com/"
simple_form_token: 5da33a3875b2782c0143c966613ebc60

build:
  days: 2
  ffmpeg_path: "C:/bramon/tools/"
  captures:
#    - "/Volumes/external/BRAMON/estacoes/!data/TLP1/"
    - "D:/bramon/!data"
    - "E:/bramon/!data"
    - "F:/bramon/!data"
    - "G:/bramon/!data"
    - "H:/bramon/!data"

stations:
  - TLP1
  - TLP2
  - TLP3
  - TLP4
  - TLP5
  - TLP6
  - TLP7
  - TLP8
  - TLP9
  - TLP10

exclude:
  - bin
  - docker-compose.yml

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

sass:
  style: compressed

collections:
  captures:
    output: true

  stations:
    output: true

  watches:
    output: true
