# Site settings
title: Meteoros Floripa
description: Estações de capturas de meteoros em Florianópolis/SC
url: "https://meteoros.floripa.br"
baseurl: "/"

# Build settings
highlighter: rouge
timezone: America/Sao_Paulo
permalink: pretty
exclude:
  - requirements.txt
  - docker-compose.yml
  - .bin
  - .idea
  - .github

# Pagination
paginate: 15
pagination_path: "/:num"

# Use your search engine ID
google_analytics: "UA-148905542-1"

# S3 bucket base address
s3_bucket: "https://meteoros.s3.amazonaws.com/"

# Facebook App ID
facebook_app_id: "2497397260472875"

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-paginate

# Sass
sass:
  style: compressed

# Collections used
collections:
  captures:
    output: true

  stations:
    output: true
