title: Meteoros Floripa
description: Estações de capturas de meteoros em Florianópolis/SC
url: "https://meteoros.floripa.br"
baseurl: "/"
location: "Florianópolis-SC"
encoding: UTF-8
highlighter: rouge
timezone: UTC
permalink: pretty
paginate: 15
pagination_path: "/:num"
google_analytics: "UA-148905542-1"
s3_bucket: "https://meteoros.s3.amazonaws.com/"

exclude:
  - requirements.txt
  - docker-compose.yml
  - .bin
  - .idea
  - .github

plugins:
  - jekyll-sitemap
  - jekyll-paginate

sass:
  style: compressed

collections:
  captures:
    output: true

  stations:
    output: true
