title: Meteoros Floripa
description: Estações de capturas de meteoros em Florianópolis/SC
url: "https://www.meteoros.floripa.br"
baseurl: "/"
city: "Florianópolis-SC"
encoding: UTF-8
highlighter: rouge
timezone: UTC
permalink: pretty
paginate: 24
pagination_path: "/:num"
google_analytics: "UA-148905542-1"
storage_url: "https://storage.meteoros.floripa.br/"
simple_form_token: 5da33a3875b2782c0143c966613ebc60
ffmpeg_path: "C:/bramon/tools"
build:
  days: 7
  captures:
    - "C:/bramon/!data"

stations:
  - TLP1
  - TLP2
  - TLP3
  - TLP4
  - TLP5
  - TLP6
  - TLP7
  - TLP8
  - TLP9
  - TLP10

exclude:
  - bin
  - docker-compose.yml

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

sass:
  style: compressed

collections:
  captures:
    output: true

  stations:
    output: true

  watches:
    output: true
