# Site settings
title: Meteoros Floripa
description: Estações de capturas de meteoros em Florianópolis/SC
url: "https://meteoros.floripa.br"
baseurl: "/"

# Build settings
highlighter: rouge
timezone: America/Sao_Paulo
permalink: pretty

# Pagination
paginate: 30
pagination_path: "/:num"

# Use your search engine ID
google_analytics: "UA-148905542-1"

# S3 bucket base address
s3_bucket: "https://meteoros.s3.amazonaws.com/"

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-paginate

sass:
  style: compressed

collections:
  captures:
    output: false
