version: '3.4'
services:
  jekyll:
    image: starefossen/github-pages
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    environment:
      - POSTGRES_DB=gateway_development
    tty: true
