name: Clean

on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Remove OS X
      uses: actions/aws/cli@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
        AWS_DEFAULT_REGION: ${{ secrets.aws_default_region }}
      with:
        args: s3 rm s3://meteoros/ --recursive --exclude "*" --include "*/.DS_Store"

    - name: Remove false captures
      uses: actions/aws/cli@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
        AWS_DEFAULT_REGION: ${{ secrets.aws_default_region }}
      with:
        args: s3 rm s3://meteoros/ --recursive --exclude "*" --include "*/._*"
